# Generated by Django 4.1.4 on 2022-12-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustRegdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('PASSWORD', models.CharField(blank=True, max_length=50, null=True)),
                ('CONPWD', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
